name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    #- name: Setup Gradle
    #  uses: gradle/actions/setup-gradle@v4

    - name: Debug Repository Files
      run: ls -la gradlew gradle/wrapper || echo "Gradle wrapper files are missing!"

    - name: Ensure Gradle Wrapper Executable
      run: chmod +x gradlew || echo "gradlew not found!"

    - name: Test with Gradle Wrapper
      run: ./gradlew test